from datetime import date

DEMO_TRANSACTIONS = [
    {"date": date(2025,2,1), "description": "Swiggy order", "category": "Food", "amount": 420},
    {"date": date(2025,2,1), "description": "BMTC Monthly Pass", "category": "Transport", "amount": 850},
    {"date": date(2025,2,2), "description": "Zomato dinner", "category": "Food", "amount": 680},
    {"date": date(2025,2,3), "description": "Amazon shopping", "category": "Shopping", "amount": 3200},
    {"date": date(2025,2,4), "description": "Netflix subscription", "category": "Entertainment", "amount": 649},
    {"date": date(2025,2,4), "description": "Ola cab", "category": "Transport", "amount": 320},
    {"date": date(2025,2,5), "description": "Big Basket groceries", "category": "Food", "amount": 2800},
    {"date": date(2025,2,6), "description": "Rent payment", "category": "Rent", "amount": 18000},
    {"date": date(2025,2,7), "description": "Swiggy Instamart", "category": "Food", "amount": 560},
    {"date": date(2025,2,8), "description": "Uber auto", "category": "Transport", "amount": 180},
    {"date": date(2025,2,9), "description": "Dominos pizza", "category": "Food", "amount": 750},
    {"date": date(2025,2,10), "description": "BESCOM electricity", "category": "Utilities", "amount": 1240},
    {"date": date(2025,2,10), "description": "Myntra clothes", "category": "Shopping", "amount": 4800},
    {"date": date(2025,2,11), "description": "Spotify premium", "category": "Entertainment", "amount": 119},
    {"date": date(2025,2,12), "description": "Rapido bike", "category": "Transport", "amount": 95},
    {"date": date(2025,2,13), "description": "Swiggy Genie", "category": "Food", "amount": 340},
    {"date": date(2025,2,14), "description": "BookMyShow movies", "category": "Entertainment", "amount": 1800},
    {"date": date(2025,2,14), "description": "Zomato Valentine", "category": "Food", "amount": 2200},
    {"date": date(2025,2,15), "description": "Apollo pharmacy", "category": "Health", "amount": 890},
    {"date": date(2025,2,16), "description": "Airtel broadband", "category": "Utilities", "amount": 999},
    {"date": date(2025,2,17), "description": "Zepto groceries", "category": "Food", "amount": 1200},
    {"date": date(2025,2,18), "description": "Flipkart sale", "category": "Shopping", "amount": 6500},
    {"date": date(2025,2,19), "description": "Ola cab airport", "category": "Transport", "amount": 780},
    {"date": date(2025,2,20), "description": "Swiggy lunch", "category": "Food", "amount": 390},
    {"date": date(2025,2,21), "description": "Cult.fit gym", "category": "Health", "amount": 2500},
    {"date": date(2025,2,22), "description": "Nykaa beauty", "category": "Shopping", "amount": 1800},
    {"date": date(2025,2,23), "description": "Zomato order", "category": "Food", "amount": 510},
    {"date": date(2025,2,24), "description": "YouTube Premium", "category": "Entertainment", "amount": 189},
    {"date": date(2025,2,25), "description": "Uber cab", "category": "Transport", "amount": 420},
    {"date": date(2025,2,26), "description": "D-Mart groceries", "category": "Food", "amount": 1900},
    {"date": date(2025,2,27), "description": "BWSSB water bill", "category": "Utilities", "amount": 380},
    {"date": date(2025,2,28), "description": "Swiggy late dinner", "category": "Food", "amount": 610},
]